apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - db/pvc.yaml
  - db/deployment.yaml
  - db/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
images:
  - name: ghcr.io/chr-devops/app-backend
    newTag: main-87435108e05888a93a37a5d1ebd83e37a6894451
  - name: ghcr.io/chr-devops/app-frontend
    newTag: main-87435108e05888a93a37a5d1ebd83e37a6894451
