apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - db/pvc.yaml
  - db/deployment.yaml
  - db/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
images:
  - name: ghcr.io/chr-devops/app-backend
    newTag: main-bdac353abe521380cb8c88c78968cb6870f052cb
  - name: ghcr.io/chr-devops/app-frontend
    newTag: main-bdac353abe521380cb8c88c78968cb6870f052cb
