apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - db/pvc.yaml
  - db/deployment.yaml
  - db/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
images:
  - name: ghcr.io/chr-devops/app-backend
    newTag: major-changes-4a833ae632a4913ed51d5eed796cada705e833c2
  - name: ghcr.io/chr-devops/app-frontend
    newTag: major-changes-4a833ae632a4913ed51d5eed796cada705e833c2
