apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: prod
type: Opaque
data:
  users: c2NvYWxhOiQyeSQwNSRCYm9BZ0dWdXRDeDFBc2VmcGRLR1UuQjZqWENMc1RDS05lZDNmRGQ5R0ZrdTU1WVg0Qy5sZQ==
