apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      color: green
  template:
    metadata:
      labels:
        app: frontend
        color: green
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/chr-devops/app-frontend:main-34fa4c10b1597b128bbecd46655ab8817d477e1b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DEPLOY_COLOR
              value: "green"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
