apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      color: blue
  template:
    metadata:
      labels:
        app: frontend
        color: blue
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: ghcr.io/chr-devops/app-frontend:main-46bcad40f6e10f5ed047badb80c334c531a8cdc5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: DEPLOY_COLOR
              value: "blue"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
