apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - namespace.yaml
  - configmap.yaml
  - db/pvc.yaml
  - db/deployment.yaml
  - db/service.yaml
  - backend-blue-deployment.yaml
  - backend-green-deployment.yaml
  - frontend-blue-deployment.yaml
  - frontend-green-deployment.yaml
  - backend-blue-service.yaml
  - backend-green-service.yaml
  - frontend-blue-service.yaml
  - frontend-green-service.yaml
  - ingress.yaml
  - auth-secret.yaml
  - auth-middleware.yaml
  - monitor-serviceaccount.yaml
  - monitor-role.yaml
  - monitor-rolebinding.yaml
  - monitor-configmap.yaml
  - monitor-deployment.yaml
