apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - db/pvc.yaml
  - db/deployment.yaml
  - db/service.yaml
  - backend-rollout.yaml
  - frontend-rollout.yaml
  - backend-active-service.yaml
  - backend-preview-service.yaml
  - frontend-active-service.yaml
  - frontend-preview-service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/chr-devops/app-backend
    newTag: "main-7fe8900afcc56d8619740f2a95d64a5420a0c764"
  - name: ghcr.io/chr-devops/app-frontend
    newTag: "main-7fe8900afcc56d8619740f2a95d64a5420a0c764"
