apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-green-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CHR-DevOps/app-infrastructure.git
    targetRevision: main
    path: kubernetes/prod-green
  destination:
    server: https://kubernetes.default.svc
    namespace: prod-green
  syncPolicy:
    automated:
      prune: true
      selfHeal: true