name: Infra Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-central-1
      AWS_REGION: eu-central-1
      TF_VAR_github_username: ${{ secrets.GIT_USERNAME }}
      TF_VAR_ghcr_token: ${{ secrets.GHCR_TOKEN_ARGOCD }}
      TF_VAR_git_branch: ${{ github.ref_name }}
      TF_VAR_key_name: devops-key

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init -reconfigure -input=false \
            -backend-config="bucket=chr-devops-terraform-s3-state" \
            -backend-config="key=app-infrastructure/prod/terraform.tfstate" \
            -backend-config="region=eu-central-1"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false